### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by mhoye** [gijsk/triage-helper#7]
Not sure what to do about this, error is: 

1430423686764   Services.Metrics.Provider.org.mozilla.addons    WARN    Add-on type without field: greasemonkey-user-script
1430423686863   addons.xpi  WARN    Exception running bootstrap method startup on triage-helper@gijsk.com: TypeError: todo is not a function (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/mhoye/Library/Application%20Support/Firefox/Profiles/0nkgth40.default-1428955983818/extensions/triage-helper@gijsk.com.xpi!/bootstrap.js:44) JS Stack trace: forEachOpenWindow@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/mhoye/Library/Application%20Support/Firefox/Profiles/0nkgth40.default-1428955983818/extensions/triage-helper@bootstrap.js:44:1 < startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/mhoye/Library/Application%20Support/Firefox/Profiles/0nkgth40.default-1428955983818/extensions/triage-helper@bootstrap.js:20:1 < XPI_callBootstrapMethod@XPIProvider.jsm:4525:9 < AI_startInstall/<@XPIProvider.jsm:5924:13 < TaskImpl_run@Task.jsm:330:41 < Handler.prototype.process@Promise-backend.js:867:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:746:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:688:37 < Promise*this.PromiseWalker.scheduleWalkerLoop@Promise-backend.js:688:5 < this.PromiseWalker.schedulePromise@Promise-backend.js:709:7 < this.PromiseWalker.completePromise@Promise-backend.js:671:7 < this.BasePromiseWorker.prototype._worker/worker.onmessage@PromiseWorker.jsm:231:9

**Comment by gijsk** [comment]
Should be fixed on current master with https://addons.mozilla.org/en-US/firefox/addon/triage-helper/versions/?page=1#version-0.1.3 . Should also have worked after a restart. Not sure why I didn't notice this before, though. Thanks for filing!
