### ISSUE TITLE
Add checkbox for "add in-triage keyword"

### ISSUE THREAD

**Issue by mhoye** [gijsk/triage-helper#8]
As part of the workflow some external tooling is going to look for the "in-triage" keyword in the bugs. Can we add a checkbox to automatically add that in?

**Comment by gijsk** [comment]
Yes. I'm a little confused what you mean, though - you want a checkbox on every page that does this when ticked? Or a pref in the add-on?

Right now there are a number of actions you can take from inside the add-on box. I'm _guessing_ the UI you're after is adding a checkbox there, and pursuing any action (that does not close the bug outright) should add that keyword. Is that interpretation correct?

**Comment by mhoye** [comment]
Correct!

**Comment by gijsk** [comment]
This should be in https://addons.mozilla.org/en-US/firefox/addon/triage-helper/versions/?page=1#version-0.1.5 .
